import { useCallback, useEffect, useState } from "react";
import api from "../../services/api";
import Card from "../../components/Card";
import LoadingScreen from "../../components/LoadingScreen";
import { useToast } from "../../context/ToastContext";

export default function AdminCalendar(){
 const {showToast}=useToast(); const now=new Date(); const [year,setYear]=useState(now.getFullYear()); const [month,setMonth]=useState(now.getMonth()+1); const [days,setDays]=useState(null); const [employees,setEmployees]=useState([]); const [leaves,setLeaves]=useState([]); const [form,setForm]=useState({calendar_date:"",day_type:"working_day",is_working_day:true,name:""}); const [leave,setLeave]=useState({employee_id:"",leave_date:"",leave_type:"paid",is_additional:false,reason:""});
 const load=useCallback(async()=>{const [c,e,l]=await Promise.all([api.get(`/calendar/month?year=${year}&month=${month}`),api.get("/admin/employees?is_active=true"),api.get("/calendar/admin/leave")]);setDays(c.data);setEmployees(e.data);setLeaves(l.data)},[year,month]); useEffect(()=>{load()},[load]);
 if(!days)return <LoadingScreen/>;
 async function saveCalendar(){if(!form.calendar_date)return;try{await api.put(`/calendar/admin/date/${form.calendar_date}`,null,{params:{day_type:form.day_type,is_working_day:form.is_working_day,name:form.name||undefined}});showToast("Calendar updated.");load()}catch(e){showToast(e?.response?.data?.detail||"Couldn't update calendar.","error")}}
 async function grant(){try{await api.post("/calendar/admin/leave",null,{params:leave});showToast("Leave granted.");setLeave({...leave,reason:""});load()}catch(e){showToast(e?.response?.data?.detail||"Couldn't grant leave.","error")}}
 async function cancel(id){try{await api.delete(`/calendar/admin/leave/${id}`,{params:{reason:"Cancelled by administrator"}});showToast("Leave cancelled.");load()}catch(e){showToast(e?.response?.data?.detail||"Couldn't cancel leave.","error")}}
 return <div className="space-y-5"><div className="flex items-center justify-between flex-wrap gap-3"><h1 className="text-xl font-semibold text-ink">Calendar & Leave</h1><div className="flex gap-2"><button className="rounded-lg border px-3 py-1.5" onClick={()=>month===1?(setYear(year-1),setMonth(12)):setMonth(month-1)}>‹</button><span className="py-1.5 text-sm font-medium min-w-28 text-center">{new Date(year,month-1,1).toLocaleString(undefined,{month:"long",year:"numeric"})}</span><button className="rounded-lg border px-3 py-1.5" onClick={()=>month===12?(setYear(year+1),setMonth(1)):setMonth(month+1)}>›</button></div></div>
 <Card><h2 className="font-semibold mb-3">Set company date</h2><div className="grid md:grid-cols-4 gap-3"><input type="date" value={form.calendar_date} onChange={e=>setForm({...form,calendar_date:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><select value={form.day_type} onChange={e=>setForm({...form,day_type:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"><option value="working_day">Working day</option><option value="sunday">Sunday</option><option value="holiday">Holiday</option><option value="other_non_working">Other non-working</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_working_day} onChange={e=>setForm({...form,is_working_day:e.target.checked})}/> Working</label><div className="flex gap-2"><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="min-w-0 flex-1 rounded-xl border px-3 py-2.5 text-sm"/><button onClick={saveCalendar} className="rounded-xl bg-ink text-white px-4 text-sm">Save</button></div></div></Card>
 <Card><div className="grid grid-cols-7 gap-1 text-center text-xs text-slate-muted mb-2">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x}>{x}</div>)}</div><div className="grid grid-cols-7 gap-1">{days.map(d=><button key={d.calendar_date} onClick={()=>setForm({calendar_date:d.calendar_date,day_type:d.day_type,is_working_day:d.is_working_day,name:d.name||""})} className={`min-h-16 rounded-lg border p-1.5 text-left ${d.is_working_day?"bg-white":"bg-slate-50"}`}><div className="text-xs font-medium">{Number(d.calendar_date.slice(-2))}</div><div className="text-[10px] mt-1 truncate">{d.name||d.day_type.replaceAll("_"," ")}</div></button>)}</div></Card>
 <Card><h2 className="font-semibold mb-3">Grant leave</h2><div className="grid md:grid-cols-5 gap-3"><select value={leave.employee_id} onChange={e=>setLeave({...leave,employee_id:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name} ({e.employee_code})</option>)}</select><input type="date" value={leave.leave_date} onChange={e=>setLeave({...leave,leave_date:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><select value={leave.leave_type} onChange={e=>setLeave({...leave,leave_type:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"><option value="paid">Paid</option><option value="sick">Sick</option><option value="unpaid">Unpaid</option></select><input placeholder="Reason" value={leave.reason} onChange={e=>setLeave({...leave,reason:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><button onClick={grant} className="rounded-xl bg-ink text-white px-4 text-sm">Grant leave</button></div><p className="text-xs text-slate-muted mt-2">Additional paid/sick leave is restricted to Super Admin. Admins can grant unpaid only after the standard paid and sick allocations are used.</p></Card>
 <Card><h2 className="font-semibold mb-3">Leave records</h2><div className="space-y-2">{leaves.filter(x=>x.status==="approved").map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-2 border-b last:border-0 py-2 text-sm"><span>{employees.find(e=>e.id===x.employee_id)?.name||x.employee_id} · {x.leave_date}</span><span className="capitalize">{x.leave_type}{x.is_additional?" · additional":""}</span><button onClick={()=>cancel(x.id)} className="text-danger text-xs">Cancel</button></div>)}{leaves.filter(x=>x.status==="approved").length===0&&<p className="text-sm text-slate-muted">No active leave records.</p>}</div></Card></div>
}
